version: '3.7'

services:
  node-app:
    build: .
    image: node-app
    env_file: ./.env
    environment:
      - MONGODB_URL=mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongodb:27017/$MONGODB_DATABASE
    ports:
      - '8001:8001'
    depends_on:
      - mongodb
    networks:
      - node-network
    command: yarn start
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:4.2.1-bionic
    env_file: ./.env
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge